name: sast

on: [push, pull_request]

jobs:
  flawfinder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependency
        run: |
          sudo apt-get install -y flawfinder
      - name: Runs flawfinder
        run: |
          flawfinder .

  cppcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependency
        run: |
          sudo apt-get install -y cppcheck
      - name: Runs cppcheck
        run: |
          cppcheck --force .

  infer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependency
        run: |
          sudo apt-get install -y libgnutls28-dev libstdc++6
      - name: Runs Infer
        run: |
          VERSION=1.1.0
          curl -sSL "https://github.com/facebook/infer/releases/download/v$VERSION/infer-linux64-v$VERSION.tar.xz" | sudo tar -C /opt -xJ
          sudo ln -s "/opt/infer-linux64-v$VERSION/bin/infer" /usr/local/bin/infer
          ./configure
          infer --progress-bar-style plain --quiet -- make
          cat infer-out/bugs.txt